version: '3.8'

services:
  jupyter:
    build: .
    ports:
      - "${PORT:-8888}:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PORT=${PORT:-8888}
    restart: unless-stopped